### ISSUE TITLE
GPU mode does not work

### ISSUE THREAD

**Issue by OuIChien** [qubic-li/client#22]
![375d0f3e0556c666421f6e34629f2fd](https://github.com/qubic-li/client/assets/950814/5ef322d2-a640-458e-bec2-88c67564a813)
![Weixin Image_20240224110909](https://github.com/qubic-li/client/assets/950814/3a513c54-caf1-4b10-b671-3efa2985ca28)

Error Info:
0 CUDA devices are used

GPU Devices: 6 pieces of Nvidia 3070
GPU Driver Version: 551.61
CUDA Version: 12.4
Operation System: Windows 10 -> WSL Ubuntu
Environment Variables: CUDA_VISIBLE_DEVICES=0,1,2,3,4,5

appsettings.json: 
"allowHwInfoCollect": true,
"overwrites": {"CUDA": "12"}

Questions:
Is it possible to mine on GPU mode?

**Comment by urrudelu30** [comment]
Same issue with CUDA 12.3 in a GTX 1650

**Comment by hakatu** [comment]
Same issue with GTX 1060

**Comment by OuIChien** [comment]
> Same issue with CUDA 12.3 in a GTX 1650, in my case CUDA Version is 98, I know that it is possible to mine with GPU due to one friend is minning. Did you fix the issue?

Hey bro, sorry it took so long to get back to you. Yes, I fixed it by using Hiveos, don't use windows.

**Comment by OuIChien** [comment]
> Same issue with GTX 1060

Use Hiveos to solve it

**Comment by OuIChien** [comment]
Use ubuntu system or Hiveos system.
