### ISSUE TITLE
May I ask what the problem is?

### ISSUE THREAD

**Issue by newstarting888** [qubic-li/client#36]
The system is Ubuntu 22.04, which was normal before this upgrade, but after the upgrade, there was a problem, and the re-installation did not boot

![image](https://github.com/qubic-li/client/assets/63486343/b0f14f62-e344-4ddc-a544-eb51aad0f145)
![image](https://github.com/qubic-li/client/assets/63486343/2ce5f3fe-5d16-4089-9055-711b568023c8)

**Comment by BBQFIL** [comment]
for i in `ps -e | grep qli-runner |awk '{print $1}' `;do kill -9 $i ;done

**Comment by newstarting888** [comment]
This process cannot be found (qli-runner)

**Comment by J0ET0M** [comment]
looks like multiple instances are running. restart the rig can help.
