### ISSUE TITLE
I keep getting AVX2 as trainer version, despite having AVX512 enabled

### ISSUE THREAD

**Issue by 2J4YZ** [qubic-li/client#46]
I have 7950X and and AVX512 enabled in BIOS but keep getting AVX2 trainer version.

**Comment by SevenXP** [comment]
@2J4YZ  tries

appsetings.json
{
  "Settings": {
    "baseUrl": "https://mine.qubic.li/",
    "overwrites": {
    "AVX512": true
    },
    "accessToken": "YOURACCESSTOKEN",
    "amountOfThreads": 32,
    "alias": "YOURALIAS"
  }
}

**Comment by BenjaminLeonhardt** [comment]
I have the same problem with 7800x3D. AVX512 is in the mainboad UEFI activated.
I verified it with CPU-Z.
Version is 1.8.7.1 and 1.8.8 both with the same problem.
![exception](https://github.com/qubic-li/client/assets/22215339/3eb7d1a4-8f8a-4470-adef-c6b5fa0047f6)

my appsetting.json 
{
  "Settings": {
    "baseUrl": "https://mine.qubic.li/",
    "allowHwInfoCollect": true,
    "overwrites": {"CUDA": "12","AVX512": true },
    "amountOfThreads": 16,
    "accessToken": "",
    "alias": "Benjamin Leonhardt"
  }
}
The GPU is as well not detected... its a RTX4080.
I get an exception as you can see on the screenshot attached.

**Comment by lukyrys** [comment]
Same problem, run only with AVX2 not AVX512, 7900X3D 
![obrazek](https://github.com/qubic-li/client/assets/2318346/d3f77136-4f5b-4154-9201-9023a59406eb)
![obrazek](https://github.com/qubic-li/client/assets/2318346/6ee7b0b2-99e7-4660-ae88-fed4fd7a3389)
 ```
 {
  "Settings": {
    "baseUrl": "https://mine.qubic.li/",
    "payoutId": "",
    "alias": "LuRy",
	"overwrites": {"CUDA": "12","AVX512": true },
	"allowHwInfoCollect": true,
	"amountOfThreads": 23,
  }
}
 ```

**Comment by J0ET0M** [comment]
it is the current version. that is correct.

**Comment by HyeokSuLee** [comment]
same

**Comment by 2J4YZ** [comment]
> it is the current version. that is correct.

What does this mean? Do you mean that AVX2 over AVX512 is intended? What about those of us that can support AVX512?


> @2J4YZ tries
> 
> appsetings.json { "Settings": { "baseUrl": "https://mine.qubic.li/", "overwrites": { "AVX512": true }, "accessToken": "YOURACCESSTOKEN", "amountOfThreads": 32, "alias": "YOURALIAS" } }

I have tried the overwrite in the config file but still only get AVX2.

**Comment by cscholl20** [comment]
Could allowHwInfoCollect be a root cause here? I tried adding it to my appsettings.json to see if maybe that was needed to allow for finding AVX-512 capabilities instead of the overwrites option

**Comment by KirillSamoilenko** [comment]
same here

**Comment by emike09** [comment]
i9-10920X and i5-11600K, same issues. Tried a few various appsettings configurations, just defaults to AVX2.

**Comment by nejib1** [comment]
Hello all, AVX512  works only in Linux, not windows.
