### ISSUE TITLE
dual xeon it/s  sometimes  varies in each run (low/high)

### ISSUE THREAD

**Issue by Sky1880** [qubic-li/client#47]
dual xeon e5 2696v3 it/s   sometimes  varies in each run and during mining from, from 15-25 it/s not more, to 79 i/s max,
i have to execute repeatedly to get that 79 it/s , and during mining it happens to

**Comment by J0ET0M** [comment]
we see variance in it/s if cooling is not optimal. OS tend to slow down CPU if it is getting hot.

**Comment by Sky1880** [comment]
temperatures are right it happens sometimes when i exucute the miner included when cpu has been idle.
here temperatures:
![temp e5-2696v3](https://github.com/qubic-li/client/assets/163621184/358fb604-b0da-4885-946c-957374d21da5)
example of low hashrate:
![temp 2 bug](https://github.com/qubic-li/client/assets/163621184/b53c1dda-ad07-4a45-8eb0-aab29cad398f)
