### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by ItzMiracleOwO** [qubic-li/client#48]
Hi, I have a few questions here.

1. My access token on `https://app.qubic.li/main/mining/pool` changes every time I refresh the page, then which token should I put in the config file for qublic client?

2. I tried to use the wallet id for the client, it has been running for 10 hours now but it still says SOL 0/0, and there are 0 qubic on my wallet, is that normal? My CPU is AMD Ryzen 9 7950X, what hash rate should I expect and for how long I get one solution?

Thanks

**Comment by J0ET0M** [comment]
1. keep only one
2. yes. please get more info in our discord.
