### ISSUE TITLE
Version 1.9.6 does not support AMD CPU, which will cause the AMD server to crash and no computing power will be generated.

### ISSUE THREAD

**Issue by catspa3** [qubic-li/client#93]
Version 1.9.6 does not support AMD CPU, which will cause the AMD server to crash and no computing power will be generated.
![image](https://github.com/qubic-li/client/assets/155090659/0b992274-ebda-4b1f-b7a3-574bf78d467f)

**Comment by catspa3** [comment]
In version 1.9.4, AMD CPU can reach 600it/s, 1.9.6 only has 1-4it/s, and will cause the AMD server to crash after running 100% of the memory.

**Comment by HyeokSuLee** [comment]
crash issue with 7950x too.
